language: python
python:
  - 2.7

# Install
install:
  - sudo apt-get -q update
  - sudo apt-get -q install gfortran libblas-dev libatlas-dev liblapack-dev
  - pip install python-coveralls
  - pip install coverage
  - python setup.py -q install

# Test
script: 
  - nosetests --with-coverage

# Coveralls
after_success:
  - coveralls