language: python
python:
  - 2.7

# Install
install:
  # Install conda
  - sudo pip install conda
  # Install dependencies
  - sudo conda init
  - sudo conda update conda --yes
  - deps='pip atlas numpy scipy pandas statsmodels scikit-learn bokeh pillow nose'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # Install your own package into the environment
  - sudo python setup.py install

# Test
script: nosetests -v